version: "3.8"
services:
  linux:
    container_name: linux
    volumes:
      - ./src:/irondome
      - ./src/config/supervisord.conf:/etc/supervisor/supervisord.conf
    working_dir: /irondome
    environment:
      - DEBIAN_FRONTEND=noninteractive
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile